name: example
description: "A Flutter example project demonstrating all the animated text widgets from my_animated_text, showcasing SlideText, TypewriterText, WaveMotionText, WavingGradientText, ShimmerText, FadeText, ScaleText, RotationText, MarqueeText, FallingText, and ColorizedText with different styles and animation modes."
version: 0.0.1+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  my_animated_text:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
