name: my_animated_text
description: "A Flutter package with customizable animated text widgets for dynamic and engaging text effects."
version: 2.0.0
homepage: https://github.com/tz-thantzin/my_animated_text
repository: https://github.com/tz-thantzin/my_animated_text
issue_tracker: https://github.com/tz-thantzin/my_animated_text/issues
maintainer: ThantZin (@tz-thantzin)
publisher: devthantzin.com

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


